sudo: required
language: node_js

services:
  - docker

node_js:
  - 8

env:
  global:
    - SHA=$(git rev-parse HEAD)

cache:
  directories:
    - node_modules

before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d

before_script:
  - npm i -g gulp

script:
  - cd public/semantic && gulp build && cd ../..
  - npm run build
  - npm test

after_success:
  - docker image build -t $DOCKER_USERNAME/$DOCKER_IMAGE:latest -t $DOCKER_USERNAME/$DOCKER_IMAGE:$SHA .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/$DOCKER_IMAGE:latest
  - docker push $DOCKER_USERNAME/$DOCKER_IMAGE:$SHA