FROM node:11-alpine

RUN npm i -g gulp

WORKDIR /app

COPY ./package.json ./
COPY ./semantic.json ./
COPY ./public/semantic ./public/semantic

RUN npm install
RUN cd public/semantic && gulp build

COPY . .

CMD ["npm", "run", "start"]